### PR TITLE
Update taskexecution.tex

### PR DESCRIPTION
**Pull request by sanctusgee**
typo in sentence. Modified wall following to "wall following"

### CODE REVIEW

**Comment by sanctusgee** [comment]
Hello team, I added a pull request based on typo in chapter. Thank you for such an amazing book

**Review by correll — COMMENTED** [review]
We only use quotes when referring to the state (the node on the state diagram), not the activity itself, so the current version should be correct. Please also use `` and '' for opening and closing quotes.

**Comment by correll** [comment]
> Hello team, I added a pull request based on typo in chapter. Thank you for such an amazing book

Thanks!

**Review by alecive — COMMENTED** [review]
I'm reopening so that you will be able to push the correct changes: as @correll said, please use `` and '' . Thanks!

**Comment by sanctusgee** [comment]
closing. request handled in PR# 74

**Pull request closed without merging**
